# 블로그 이름
title : FitCloud 기술 블로그

# 블로그 이름 밑에 들어가는 설명 글
tagline : Saltware에서 운영하는 기술 블로그 입니다.

# 웹페이지 주소
url : https://cubit20.github.io/originBlog_00.github.io/

# 작성자 이름, 페이지 하단에 표시
author : Saltware_FitCloud

# 프로필 이미지 설정
avtar : 

# 이메일, 깃허브, 트위터 등등
social : csm@saltware.co.kr

# 시간설정
timezone : Asia/Seoul
